#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""


from pandas import read_excel
from pandas import DataFrame
import numpy as np

import statsmodels.api as sm
from matplotlib import pyplot


excel_data_df = read_excel('sakaryagunluktoplamsatislar1620_2.xlsx', sheet_name='sheet1')

excelX = np.asarray(excel_data_df['TARIH'])
print(excelX)


#print(excel_data_df['MIKTAR']) 
#mod = sm.tsa.statespace.SARIMAX(excel_data_df['MIKTAR'],excelX, order=(1,1,1),seasonal_order=(1,1,1,12))
#res = mod.fit();
#print(res.summary());
#excel_data_df['forecast']=res.predict(start=1,end=1000,dynamic=True)
#excel_data_df[['MIKTAR','forecast']].plot(figsize=(12,8))
